Repository apify/apify-client-python, pull requests merged in 2022-12, with the labels that each got.

#85 Catch up to JS client
  CHANGELOG.md
  README.md
  docs/docs.md
  src/apify_client/_http_client.py
  src/apify_client/clients/base/resource_collection_client.py
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/actor_env_var.py
  src/apify_client/clients/resource_clients/actor_env_var_collection.py
  src/apify_client/clients/resource_clients/actor_version.py
  src/apify_client/clients/resource_clients/dataset.py
  src/apify_client/clients/resource_clients/dataset_collection.py
  src/apify_client/clients/resource_clients/key_value_store_collection.py
  src/apify_client/clients/resource_clients/schedule.py
  src/apify_client/clients/resource_clients/schedule_collection.py
  src/apify_client/clients/resource_clients/task.py
  src/apify_client/clients/resource_clients/task_collection.py
  src/apify_client/consts.py
Labels: t-platform

#87 Disallowed `NaN` and `Infinity` values in JSONs sent to the Apify API
  CHANGELOG.md
  src/apify_client/_http_client.py
  src/apify_client/_utils.py
Labels: bug, adhoc, t-platform

#90 Added `pre-commit` to run code quality checks before committing
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  setup.py
Labels: adhoc, t-platform

#91 Converted `unittest`-style tests to `pytest`-style tests
  .isort.cfg
  CHANGELOG.md
  setup.py
  tests/unit/test_utils.py
Labels: adhoc, t-platform
