Repository apify/apify-client-python, pull requests merged in 2023-07, with the labels that each got.

#129 feat: add list_and_lock_head, delete_request_lock, prolong_request_lock, batch_add_requests, batch_delete_requests and list_requests methods
  CHANGELOG.md
  docs/docs.md
  pyproject.toml
  scripts/check_async_docstrings.py
  scripts/fix_async_docstrings.py
  src/apify_client/clients/resource_clients/request_queue.py
  tests/integration/test_request_queue.py
Labels: t-platform, tested

#134 feat(docs): Add indicator for keyword-only arguments, add link to method sources
  pyproject.toml
  website/patches/docusaurus-plugin-typedoc-api+2.5.1.patch
  website/transformDocs.js
Labels: adhoc, t-platform

#132 Start using apify-shared for general consts and utils
  .flake8
  .isort.cfg
  docs/docs.md
  docs/res/sphinx-config/index.rst
  pyproject.toml
  src/apify_client/_errors.py
  src/apify_client/_http_client.py
  src/apify_client/_types.py
  src/apify_client/_utils.py
  src/apify_client/client.py
  src/apify_client/clients/base/actor_job_base_client.py
  src/apify_client/clients/base/base_client.py
  src/apify_client/clients/base/resource_client.py
  src/apify_client/clients/base/resource_collection_client.py
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/actor_collection.py
  src/apify_client/clients/resource_clients/actor_env_var.py
  src/apify_client/clients/resource_clients/actor_env_var_collection.py
  src/apify_client/clients/resource_clients/actor_version.py
  src/apify_client/clients/resource_clients/actor_version_collection.py
  src/apify_client/clients/resource_clients/build.py
  src/apify_client/clients/resource_clients/build_collection.py
  src/apify_client/clients/resource_clients/dataset.py
  src/apify_client/clients/resource_clients/dataset_collection.py
  src/apify_client/clients/resource_clients/key_value_store.py
  src/apify_client/clients/resource_clients/key_value_store_collection.py
  src/apify_client/clients/resource_clients/log.py
  src/apify_client/clients/resource_clients/request_queue.py
  src/apify_client/clients/resource_clients/request_queue_collection.py
  src/apify_client/clients/resource_clients/run.py
  src/apify_client/clients/resource_clients/run_collection.py
  src/apify_client/clients/resource_clients/schedule.py
  src/apify_client/clients/resource_clients/schedule_collection.py
  src/apify_client/clients/resource_clients/task.py
  src/apify_client/clients/resource_clients/task_collection.py
  src/apify_client/clients/resource_clients/user.py
  src/apify_client/clients/resource_clients/webhook.py
  src/apify_client/clients/resource_clients/webhook_collection.py
  src/apify_client/clients/resource_clients/webhook_dispatch.py
  src/apify_client/clients/resource_clients/webhook_dispatch_collection.py
  src/apify_client/consts.py
  tests/unit/test_utils.py
Labels: t-tooling

#135 Rm warnings simplefilter always
  src/apify_client/clients/resource_clients/dataset.py
  src/apify_client/clients/resource_clients/key_value_store.py
Labels: t-tooling

#136 Bump version to 1.3.1
  CHANGELOG.md
  pyproject.toml
Labels: t-tooling
