Repository apify/apify-client-python, pull requests merged in 2023-10, with the labels that each got.

#154 Add release checklists
  CONTRIBUTING.md
Labels: t-tooling

#152 feat: Add run, build delete to client
  CHANGELOG.md
  pyproject.toml
  src/apify_client/clients/resource_clients/build.py
  src/apify_client/clients/resource_clients/run.py
Labels: t-c&c

#155 Add support for Python 3.12
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/unit_tests.yaml
  CHANGELOG.md
  pyproject.toml
Labels: t-tooling

#157 chore: Check whether version in PR is already released
  .github/workflows/check_version_availability.yaml
  .github/workflows/run_checks.yaml
  Makefile
  scripts/check_version_availability.py
  scripts/update_version_for_prerelease.py
  scripts/utils.py
Labels: adhoc, t-platform

#159 Add checklist for upgrading Python version
  CONTRIBUTING.md
Labels: t-tooling
