Repository apify/apify-client-python, pull requests merged in 2024-12, with the labels that each got.

#304 feat: Add charge method to the run client for "pay per event"
  src/apify_client/clients/resource_clients/run.py
Labels: t-c&c

#314 feat: Add error data to ApifyApiError
  poetry.lock
  pyproject.toml
  src/apify_client/_errors.py
  tests/unit/test_client_errors.py
Labels: enhancement, t-tooling, tested

#319 chore: relax HTTPX version upper bound
  poetry.lock
  pyproject.toml
Labels: t-tooling
