Repository apify/apify-client-python, pull requests merged in 2024-07, with the labels that each got.

#241 fix: getting storages of last run
  CHANGELOG.md
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/task.py
Labels: t-tooling

#242 chore: bump version to 1.7.2
  CHANGELOG.md
  pyproject.toml
Labels: adhoc, t-tooling

#243 chore: update dev deps & fix linter
  pyproject.toml
  scripts/fix_async_docstrings.py
  scripts/utils.py
  src/apify_client/_errors.py
  src/apify_client/_logging.py
Labels: adhoc, t-tooling

#248 feat: add actor standby
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/actor_collection.py
  src/apify_client/clients/resource_clients/task.py
  src/apify_client/clients/resource_clients/task_collection.py
Labels: adhoc, t-platform
