Repository apify/apify-client-python, pull requests merged in 2024-10, with the labels that each got.

#272 ci: use shared workflows and refactor them
  .github/workflows/_async_docstrings_check.yaml
  .github/workflows/_changelog_entry_check.yaml
  .github/workflows/_version_conflict_check.yaml
  .github/workflows/build_and_deploy_docs.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/run_checks.yaml
  .github/workflows/run_code_checks.yaml
  .github/workflows/run_release.yaml
  .github/workflows/unit_tests.yaml
  .pre-commit-config.yaml
  Makefile
  pyproject.toml
  scripts/check_async_docstrings.py
  scripts/check_changelog_entry.py
  scripts/check_version_conflict.py
Labels: adhoc, infrastructure, t-tooling

#275 ci: fix reference in run release
  .github/workflows/run_release.yaml
Labels: adhoc, infrastructure, t-tooling

#276 ci: align workflows with other repositories
  .github/workflows/build_and_deploy_docs.yaml
  Makefile
Labels: adhoc, infrastructure, t-tooling

#277 docs: bump `@apify/docusaurus-plugin-typedoc-api`
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
Labels: adhoc, t-tooling

#279 feat: add user.update_limits
  src/apify_client/clients/resource_clients/user.py
Labels: t-console

#278 ci: Automate the release process
  .github/workflows/_changelog_entry_check.yaml
  .github/workflows/_version_conflict_check.yaml
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
  .github/workflows/run_release.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  pyproject.toml
  scripts/check_changelog_entry.py
  scripts/check_version_conflict.py
  scripts/print_current_package_version.py
  scripts/update_version_for_prerelease.py
Labels: t-tooling

#281 ci: Fix release workflow
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
Labels: adhoc, t-tooling

#282 chore: update dev deps
  pyproject.toml
Labels: adhoc, t-tooling
