Repository apify/apify-client-python, pull requests merged in 2024-08, with the labels that each got.

#257 chore: Fix capitalization - actor -> Actor
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/index.md
  src/apify_client/client.py
  src/apify_client/clients/base/actor_job_base_client.py
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/actor_collection.py
  src/apify_client/clients/resource_clients/actor_env_var.py
  src/apify_client/clients/resource_clients/actor_version.py
  src/apify_client/clients/resource_clients/actor_version_collection.py
  src/apify_client/clients/resource_clients/build.py
  src/apify_client/clients/resource_clients/build_collection.py
  src/apify_client/clients/resource_clients/run.py
  src/apify_client/clients/resource_clients/run_collection.py
  src/apify_client/clients/resource_clients/schedule.py
  src/apify_client/clients/resource_clients/schedule_collection.py
  src/apify_client/clients/resource_clients/task.py
  src/apify_client/clients/resource_clients/task_collection.py
  src/apify_client/clients/resource_clients/webhook.py
  src/apify_client/clients/resource_clients/webhook_collection.py
  website/src/pages/index.js
Labels: adhoc, t-tooling

#256 feat: Allow passing list of fields to unwind parameter
  CHANGELOG.md
  src/apify_client/clients/resource_clients/dataset.py
Labels: adhoc, t-platform

#262 chore: migrate to Poetry and update tooling just like in Crawlee
  .github/workflows/check_pr_title.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/unit_tests.yaml
  .github/workflows/update_new_issue.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  mypy.ini
  pyproject.toml
  pytest.ini
  renovate.json
  scripts/update_version_for_prerelease.py
  src/apify_client/_utils.py
  src/apify_client/clients/resource_clients/dataset.py
  tests/integration/conftest.py
Labels: t-tooling, tested
