Repository apify/apify-client-python, pull requests merged in 2024-05, with the labels that each got.

#192 fix: aborting of last Actor/task run
  CHANGELOG.md
  pyproject.toml
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/task.py
Labels: t-tooling

#193 chore: bump version to 1.7.1
  CHANGELOG.md
  pyproject.toml
Labels: adhoc, t-tooling

#191 chore: Add Python Client examples [docs]
  docs/examples.md
  website/sidebars.js
Labels: t-web

#226 chore: update dev deps and gh actions pipelines
  .github/workflows/check_async_docstrings.yaml
  .github/workflows/check_version_availability.yaml
  .github/workflows/docs.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/unit_tests.yaml
  Makefile
  pyproject.toml
  renovate.json
Labels: adhoc, t-tooling, dependencies

#227 chore: update dev deps
  pyproject.toml
Labels: adhoc, t-tooling, dependencies

#233 chore: fix pytest deps (no module named pkg_resources)
  Makefile
  pyproject.toml
Labels: bug, adhoc, t-tooling

#232 docs: Added new getting started page
  docs/features.md
  docs/index.md
  docs/quick-start.md
  docs/usage-concepts.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: t-web
