Repository apify/apify-client-python, pull requests merged in 2025-08, with the labels that each got.

#452 docs: Setup docs llms plugin
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
Labels: t-web

#461 docs: attempt to fix changelog
  website/docusaurus.config.js
Labels: adhoc, t-tooling

#469 chore!: Bump minimum Python version to 3.10
  .github/workflows/run_code_checks.yaml
  pyproject.toml
  src/apify_client/clients/resource_clients/log.py
  uv.lock
Labels: adhoc, t-tooling

#475 chore: Update to apify-shared v2.0
  pyproject.toml
  src/apify_client/_http_client.py
  src/apify_client/_types.py
  src/apify_client/_utils.py
  src/apify_client/client.py
  src/apify_client/clients/base/actor_job_base_client.py
  src/apify_client/clients/base/base_client.py
  src/apify_client/clients/base/resource_client.py
  src/apify_client/clients/base/resource_collection_client.py
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/actor_collection.py
  src/apify_client/clients/resource_clients/actor_env_var.py
  src/apify_client/clients/resource_clients/actor_env_var_collection.py
  src/apify_client/clients/resource_clients/actor_version.py
  src/apify_client/clients/resource_clients/actor_version_collection.py
  src/apify_client/clients/resource_clients/build.py
  src/apify_client/clients/resource_clients/build_collection.py
  src/apify_client/clients/resource_clients/dataset.py
  src/apify_client/clients/resource_clients/dataset_collection.py
  src/apify_client/clients/resource_clients/key_value_store.py
  src/apify_client/clients/resource_clients/key_value_store_collection.py
  src/apify_client/clients/resource_clients/log.py
  src/apify_client/clients/resource_clients/request_queue.py
  src/apify_client/clients/resource_clients/request_queue_collection.py
  src/apify_client/clients/resource_clients/run.py
  src/apify_client/clients/resource_clients/run_collection.py
  src/apify_client/clients/resource_clients/schedule.py
  src/apify_client/clients/resource_clients/schedule_collection.py
  src/apify_client/clients/resource_clients/store_collection.py
  src/apify_client/clients/resource_clients/task.py
  src/apify_client/clients/resource_clients/task_collection.py
  src/apify_client/clients/resource_clients/user.py
  src/apify_client/clients/resource_clients/webhook.py
  src/apify_client/clients/resource_clients/webhook_collection.py
  src/apify_client/clients/resource_clients/webhook_dispatch.py
  src/apify_client/clients/resource_clients/webhook_dispatch_collection.py
  src/apify_client/errors.py
  uv.lock
Labels: adhoc, t-tooling

#453 feat: add dataset.create_items_public_url and key_value_store.create_keys_public_url
  src/apify_client/clients/resource_clients/dataset.py
  src/apify_client/clients/resource_clients/key_value_store.py
  tests/integration/integration_test_utils.py
  tests/integration/test_dataset.py
  tests/integration/test_key_value_store.py
  tests/integration/test_request_queue.py
  uv.lock
Labels: adhoc, t-core-services, tested

#477 docs: Update sidebar collapsed fields
  uv.lock
  website/sidebars.js
Labels: adhoc, t-tooling
