Repository apify/apify-client-python, pull requests merged in 2025-01, with the labels that each got.

#325 docs: Update charge endpoint URL
  src/apify_client/clients/resource_clients/run.py
Labels: t-c&c

#324 feat: add GET: dataset.statistics
  src/apify_client/clients/resource_clients/dataset.py
Labels: t-console

#328 ci: Add workflow dispatch for pre-release workflow
  .github/workflows/pre_release.yaml
Labels: adhoc, infrastructure, t-tooling

#336 feat: add `get_open_api_specification` method to `BuildClient`
  src/apify_client/clients/resource_clients/build.py
Labels: adhoc, t-platform

#339 refactor: rename /openapi-specification -> /openapi.json
  src/apify_client/clients/resource_clients/build.py
Labels: adhoc, t-platform

#340 docs: Move code samples to files and other updates
  Makefile
  docs/01_overview/01_introduction.mdx
  docs/01_overview/02_setting_up.mdx
  docs/01_overview/03_getting_started.mdx
  docs/01_overview/code/01_usage_async.py
  docs/01_overview/code/01_usage_sync.py
  docs/01_overview/code/02_auth_async.py
  docs/01_overview/code/02_auth_sync.py
  docs/01_overview/code/03_dataset_async.py
  docs/01_overview/code/03_dataset_sync.py
  docs/01_overview/code/03_input_async.py
  docs/01_overview/code/03_input_sync.py
  docs/02_concepts/01_async_support.mdx
  docs/02_concepts/02_single_collection_clients.mdx
  docs/02_concepts/03_nested_clients.mdx
  docs/02_concepts/04_error_handling.mdx
  docs/02_concepts/05_retries.mdx
  docs/02_concepts/06_logging.mdx
  docs/02_concepts/07_convenience_methods.mdx
  docs/02_concepts/08_pagination.mdx
  docs/02_concepts/09_streaming.mdx
  docs/02_concepts/code/01_async_support.py
  docs/02_concepts/code/02_collection_async.py
  docs/02_concepts/code/02_collection_sync.py
  docs/02_concepts/code/02_single_async.py
  docs/02_concepts/code/02_single_sync.py
  docs/02_concepts/code/03_nested_async.py
  docs/02_concepts/code/03_nested_sync.py
  docs/02_concepts/code/04_error_async.py
  docs/02_concepts/code/04_error_sync.py
  docs/02_concepts/code/05_retries_async.py
  docs/02_concepts/code/05_retries_sync.py
  docs/02_concepts/code/06_logging_config.py
  docs/02_concepts/code/06_logging_formatter.py
  docs/02_concepts/code/07_call_async.py
  docs/02_concepts/code/07_call_sync.py
  docs/02_concepts/code/08_pagination_async.py
  docs/02_concepts/code/08_pagination_sync.py
  docs/02_concepts/code/09_streaming_async.py
  docs/02_concepts/code/09_streaming_sync.py
  docs/03_examples/01_passing_input_to_actor.mdx
  docs/03_examples/02_manage_tasks_for_reusable_input.mdx
  docs/03_examples/03_retrieve_actor_data.mdx
  docs/03_examples/04_integration_with_data_libraries.mdx
  docs/03_examples/code/01_input_async.py
  docs/03_examples/code/01_input_sync.py
  docs/03_examples/code/02_tasks_async.py
  docs/03_examples/code/02_tasks_sync.py
  docs/03_examples/code/03_retrieve_async.py
  docs/03_examples/code/03_retrieve_sync.py
  docs/03_examples/code/04_pandas_async.py
  docs/03_examples/code/04_pandas_sync.py
  docs/examples.md
  docs/index.md
  pyproject.toml
  website/docusaurus.config.js
  website/generate_module_shortcuts.py
  website/sidebars.js
  website/src/pages/home_page_example.py
  website/src/pages/index.js
Labels: t-tooling
