Repository apify/apify-client-python, pull requests merged in 2025-06, with the labels that each got.

#407 feat: Add `StatusMessageWatcher`
  src/apify_client/_logging.py
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/log.py
  src/apify_client/clients/resource_clients/run.py
  tests/unit/test_logging.py
Labels: t-tooling, tested

#422 feat: allow sorting of Actors collection
  src/apify_client/clients/resource_clients/actor_collection.py
Labels: t-integrations

#427 feat: Add `KeyValueStoreClient.record_exists`
  src/apify_client/clients/resource_clients/key_value_store.py
Labels: adhoc, t-tooling
