Repository apify/apify-client-python, pull requests merged in 2025-02, with the labels that each got.

#347 docs: fix get started link
  website/src/pages/index.js
Labels: bug, adhoc, t-tooling

#350 fix: Fix return type of charge API call
  src/apify_client/clients/resource_clients/run.py
Labels: adhoc, t-tooling

#351 fix: Add missing PPE-related Actor parameters
  src/apify_client/clients/resource_clients/actor.py
Labels: adhoc, t-tooling

#352 docs: Set line length to docs related code to 90
  docs/02_concepts/code/06_logging_formatter.py
  docs/pyproject.toml
Labels: adhoc, t-tooling

#355 chore: migrate to uv package manager
  .github/workflows/_async_docstrings_check.yaml
  .github/workflows/build_and_deploy_docs.yaml
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
  .gitignore
  CONTRIBUTING.md
  Makefile
  docs/01_overview/02_setting_up.mdx
  poetry.lock
  pyproject.toml
  uv.lock
Labels: t-tooling

#356 ci: switch apify workflow branch back to main
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
Labels: t-tooling
