Repository apify/apify-client-python, pull requests merged in 2025-05, with the labels that each got.

#391 refactor: Remove redundant retries from `batch_add_requests`
  src/apify_client/clients/resource_clients/request_queue.py
  tests/unit/test_client_request_queue.py
Labels: debt, t-tooling, tested

#396 feat: Add `validate_input` endpoint
  src/apify_client/clients/resource_clients/actor.py
Labels: enhancement, t-tooling

#397 feat: add list kv store keys by collection or prefix
  src/apify_client/clients/resource_clients/key_value_store.py
Labels: t-console

#403 feat: Add redirected actor logs
  pyproject.toml
  src/apify_client/_logging.py
  src/apify_client/clients/resource_clients/actor.py
  src/apify_client/clients/resource_clients/log.py
  src/apify_client/clients/resource_clients/run.py
  tests/unit/test_logging.py
  uv.lock
Labels: t-tooling, tested
